;this file for FamiStudio Sound Engine generated by FamiStudio

music_data:
	db 1
	dw @instruments
	dw @samples-4
	dw @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4
	db <(@tempo_env_14_mid), >(@tempo_env_14_mid), 0, 0

@instruments:
	dw @env7,@env0,@env17,@env19
	dw @env6,@env0,@env17,@env8
	dw @env18,@env0,@env17,@env8
	dw @env4,@env0,@env17,@env11
	dw @env10,@env0,@env17,@env8
	dw @env5,@env0,@env17,@env8
	dw @env13,@env0,@env17,@env8
	dw @env2,@env0,@env17,@env8
	dw @env12,@env0,@env17,@env8
	dw @env9,@env0,@env16,@env15
	dw @env14,@env0,@env16,@env15
	dw @env3,@env0,@env16,@env15
	dw @env3,@env0,@env16,@env1

@samples:
	db $00+<(FAMISTUDIO_DPCM_PTR),$0d,$0f,$40	;1 (BM Bass Drum)
	db $04+<(FAMISTUDIO_DPCM_PTR),$1f,$0f,$40	;2 (BM Tom 1)
	db $0c+<(FAMISTUDIO_DPCM_PTR),$1f,$0f,$40	;3 (BM Tom 2)
	db $0c+<(FAMISTUDIO_DPCM_PTR),$1f,$0e,$40	;4 (BM Tom 2)
	db $0c+<(FAMISTUDIO_DPCM_PTR),$1f,$0c,$40	;5 (BM Tom 2)

@env0:
	db $c0,$7f,$00,$00
@env1:
	db $00,$c1,$7f,$00,$01
@env2:
	db $00,$c8,$ca,$03,$c9,$03,$c8,$00,$06
@env3:
	db $04,$cf,$7f,$00,$01
@env4:
	db $00,$c1,$c5,$c4,$c4,$c3,$00,$05
@env5:
	db $00,$c4,$ca,$02,$c1,$c5,$c4,$00,$01
@env6:
	db $00,$c3,$ca,$03,$c9,$c9,$c1,$c5,$c4,$c4,$c3,$00,$0a
@env7:
	db $04,$c5,$7f,$00,$01
@env8:
	db $00,$c1,$06,$c0,$c0,$c1,$c1,$c2,$c2,$c3,$c3,$c2,$c2,$c1,$c1,$c0,$c0,$bf,$bf,$00,$03
@env9:
	db $00,$c5,$c5,$c4,$c3,$c1,$c0,$c0,$c3,$c3,$c2,$c1,$c0,$02,$c7,$c7,$c6,$c5,$c2,$c1,$c1,$c3,$c3,$c2,$c2,$c1,$c0,$00,$1a
@env10:
	db $00,$c4,$c9,$02,$c1,$c5,$c4,$00,$01
@env11:
	db $00,$c0,$c0,$c1,$c1,$c2,$c2,$c3,$c3,$c2,$c2,$c1,$c1,$c0,$c0,$bf,$bf,$be,$be,$bf,$bf,$00,$01
@env12:
	db $00,$c9,$04,$c8,$03,$c7,$00,$05
@env13:
	db $00,$c5,$02,$c6,$c6,$c7,$c7,$c8,$00,$07
@env14:
	db $00,$c7,$c6,$c5,$c4,$c3,$00,$05
@env15:
	db $00,$c0,$7f,$00,$01
@env16:
	db $7f,$00,$00
@env17:
	db $c1,$7f,$00,$00
@env18:
	db $00,$c3,$c9,$02,$c8,$c8,$c1,$c5,$c4,$c4,$c3,$00,$0a
@env19:
	db $00,$c1,$04,$c1,$c1,$c0,$c0,$bf,$bf,$be,$be,$bd,$bd,$be,$be,$bf,$bf,$c0,$c0,$00,$03
@tempo_env_14_mid:
	db $03,$05,$05,$05,$04,$06,$05,$05,$80
@song0ch0:
	db $f7, $e7, $6b, $f7, $e7
@song0ch0loop:
	db $6a, <(@tempo_env_14_mid), >(@tempo_env_14_mid), $00, $f7, $e5, $6b, $f7, $e7
@song0ref16:
	db $6b, $00, $8b, $88
@song0ref20:
	db $24, $8b, $2b, $8b, $27, $8b, $2c, $8b, $2b, $8b, $27, $8b, $90, $24, $f7, $83, $6b, $e1, $86, $24, $99, $84, $23, $a7
	db $24, $99, $26, $99, $6b, $27, $99, $29, $8b, $90, $2b, $f7, $bb, $6b, $e1, $86, $2b, $99, $84, $2e, $a7, $2c, $99, $2b
	db $99, $6b, $29, $a7, $25, $a7, $90, $20, $f7, $91, $6b, $e1, $86, $20, $99, $88, $25, $8b, $27, $8b, $29, $8b, $2b, $8b
	db $2c, $8b, $2e, $8b, $2c, $8b, $6b, $90, $2b, $f7, $c9, $86, $2b, $99, $6b, $00, $99, $8c, $2e, $99, $86, $2e, $99, $82
	db $2e, $8b, $86, $2e, $99, $8a, $2c, $8b, $2b, $8b, $29, $8b, $2b, $8b, $29, $8b, $27, $8b, $26, $8b
	db $ff, $4e
	dw @song0ref16
	db $a7, $8a, $2b, $8b, $29, $8b, $2b, $8b, $27, $8b, $29, $8b, $26, $8b, $27, $8b, $6b, $82, $24, $a7, $2b, $a7, $30, $99
	db $32, $99, $8a, $33, $8b, $82, $30, $a7, $33, $99, $6b, $32, $a7, $33, $a7, $35, $99, $8a, $2e, $8b, $82, $2e, $99, $30
	db $a7, $32, $99, $6b, $8a
@song0ref192:
	db $33, $8b, $30, $8b, $2c, $8b, $30, $8b, $2c, $8b, $27, $8b, $2c, $8b, $27, $8b, $24, $8b, $27, $8b, $24, $8b, $20, $8b
	db $2c, $8b, $20, $8b, $22, $8b, $20, $8b, $6b
@song0ref225:
	db $1f, $8b, $26, $8b, $2b, $8b, $32, $8b, $37, $8b, $35, $8b, $33, $8b, $35, $8b, $33, $8b, $32, $8b, $30, $8b, $32, $8b
	db $30, $8b, $2f, $8b, $2d, $8b, $2f
@song0ref256:
	db $8b, $6b
@song0ref258:
	db $30, $99, $2b, $8b, $32, $99, $2b, $8b, $33, $99, $2b, $8b, $35, $8b, $33, $8b, $35, $8b, $8e, $37, $99, $86, $37, $99
	db $6b, $8a
@song0ref284:
	db $30, $99, $2c, $8b, $32, $99, $2c, $8b, $33, $99, $2c, $8b, $35, $8b, $33, $8b, $35, $8b, $8e, $37, $99, $86, $37, $99
	db $6b, $8a
@song0ref310:
	db $32, $99, $2e, $8b, $33, $99, $2e, $8b, $35, $99, $2e, $8b, $37, $8b, $35, $8b, $37, $8b, $38, $8b, $37, $8b, $35, $8b
	db $38, $8b, $6b, $82, $37, $a7, $38, $a7, $37, $a7, $8a, $32, $8b, $33, $8b, $35, $8b, $37, $8b, $35, $8b, $33, $8b, $32
	db $ff, $2d
	dw @song0ref256
	db $6b, $8a
@song0ref363:
	db $35, $99, $2e, $8b, $37, $99, $2e, $8b, $38, $99, $2e, $8b, $3a, $8b, $38, $8b, $3a, $8b, $37, $8b, $38, $8b, $35, $8b
	db $37, $8b, $6b, $82, $33, $a7, $35, $a7, $37, $99, $35, $a7, $33, $a7, $32, $99, $6b, $8e, $30, $f7, $e5, $6b, $f7, $cb
	db $86, $30, $99, $fd
	dw @song0ch0loop
@song0ch1:
	db $f7, $e7, $f7, $e7
@song0ch1loop:
	db $00, $f7, $e5, $f7, $e7, $9f, $80
	db $ff, $0c
	dw @song0ref20
@song0ref432:
	db $24, $e9, $f7, $97, $23, $a7, $24, $99, $26, $87, $91, $27, $99, $29, $8b, $2b, $f7, $a9, $f7, $97, $2e, $a7, $2c, $99
	db $2b, $87, $91, $29, $a7, $25, $a7, $20, $f7, $f7, $97, $25, $8b, $27, $8b, $29, $8b, $2b, $8b, $2c, $8b, $2e, $87, $83
	db $2c, $8b, $2b, $f7, $d3, $91, $00, $87, $8c, $29, $99, $86, $29, $99, $8e, $29, $9d, $86, $29, $99, $80, $2c, $8b, $2b
	db $8b, $29, $8b, $2b, $8b, $29, $8b, $27, $87, $83, $26, $8b, $00, $8b
	db $ff, $0c
	dw @song0ref20
	db $ff, $40
	dw @song0ref432
	db $80, $2b, $8b, $29, $8b, $2b, $8b, $27, $8b, $29, $8b, $26, $87, $83, $27, $8b, $24, $a7, $2b, $a7, $30, $99, $32, $99
	db $33, $8b, $30, $a7, $33, $87, $91, $32, $a7, $33, $a7, $35, $99, $2e, $a7, $30, $a7, $32, $87, $91
	db $ff, $1d
	dw @song0ref192
	db $87, $83, $20, $8b
	db $ff, $1d
	dw @song0ref225
	db $87, $83, $2f, $8b
	db $ff, $12
	dw @song0ref258
	db $37, $a3, $91
	db $ff, $12
	dw @song0ref284
	db $37, $a3, $91
	db $ff, $17
	dw @song0ref310
	db $87, $32, $a7, $33, $a7, $32, $c7, $33, $8b, $35, $8b, $37, $8b, $35, $8b, $33, $87, $83, $32, $8b
	db $ff, $12
	dw @song0ref258
	db $37, $a3, $91
	db $ff, $12
	dw @song0ref284
	db $37, $a3, $91
	db $ff, $17
	dw @song0ref363
	db $87, $2e, $ed, $2f, $ed, $30, $f7, $e5, $f7, $e7, $fd
	dw @song0ch1loop
@song0ch2:
@song0ref645:
	db $98
@song0ref646:
	db $24, $85, $00, $83, $24, $85, $00, $83, $27, $85, $00, $83, $24, $85, $00, $83, $29, $85, $00, $83, $22, $85, $00, $83
	db $27, $85, $00, $83, $24, $85, $00, $83
	db $ff, $20
	dw @song0ref646
	db $ff, $20
	dw @song0ref646
	db $ff, $20
	dw @song0ref646
@song0ch2loop:
	db $ff, $20
	dw @song0ref645
	db $ff, $20
	dw @song0ref646
	db $ff, $20
	dw @song0ref646
	db $ff, $20
	dw @song0ref646
	db $ff, $20
	dw @song0ref646
	db $ff, $20
	dw @song0ref646
	db $ff, $20
	dw @song0ref646
	db $ff, $20
	dw @song0ref646
	db $ff, $20
	dw @song0ref646
	db $ff, $20
	dw @song0ref646
	db $ff, $20
	dw @song0ref646
	db $ff, $20
	dw @song0ref646
@song0ref724:
	db $96
@song0ref725:
	db $25, $85, $00, $83, $25, $85, $00, $83, $98, $29, $85, $00, $83, $96, $25, $85, $00, $83, $98, $2c, $85, $00, $83, $96
	db $25, $85, $00, $83, $98, $27, $85, $00, $83, $96, $25, $85, $00, $83
	db $ff, $20
	dw @song0ref725
	db $ff, $20
	dw @song0ref725
	db $ff, $20
	dw @song0ref725
@song0ref772:
	db $1f, $85, $00, $83, $1f, $85, $00, $83, $26, $85, $00, $83, $1f, $85, $00, $83, $98, $29, $85, $00, $83, $96
@song0ref794:
	db $1f, $85, $00, $83, $98, $2b, $85, $00, $83, $96, $1f, $85, $00, $83
	db $ff, $20
	dw @song0ref772
	db $ff, $20
	dw @song0ref772
	db $1f, $85, $00, $83, $98, $2c, $85, $00, $83
@song0ref823:
	db $2b, $85, $00, $83
@song0ref827:
	db $29, $85, $00, $83, $2b, $85, $00, $83, $29, $85, $00, $83, $27, $85, $00, $83, $96, $26, $85, $00, $83
	db $ff, $20
	dw @song0ref645
	db $ff, $20
	dw @song0ref646
	db $ff, $20
	dw @song0ref646
	db $ff, $20
	dw @song0ref646
	db $ff, $20
	dw @song0ref646
	db $ff, $20
	dw @song0ref646
	db $ff, $20
	dw @song0ref646
	db $ff, $20
	dw @song0ref646
	db $ff, $20
	dw @song0ref724
	db $ff, $20
	dw @song0ref725
	db $ff, $20
	dw @song0ref725
	db $ff, $20
	dw @song0ref725
	db $ff, $20
	dw @song0ref772
	db $ff, $20
	dw @song0ref772
	db $ff, $20
	dw @song0ref772
	db $1f, $85, $00, $83, $98
	db $ff, $0c
	dw @song0ref823
	db $27, $85, $00, $83, $29, $85, $00, $83, $96, $26, $85, $00, $83, $98, $27, $85, $00, $83, $24, $85, $00, $83
@song0ref923:
	db $24, $85, $00, $83, $2b, $85, $00, $83, $24, $85, $00, $83, $2c, $85, $00, $83, $2b, $85, $00, $83, $27, $85, $00, $83
	db $96, $1f, $85, $00, $83, $98, $24, $85, $00, $83, $96
	db $ff, $18
	dw @song0ref923
	db $1f
@song0ref962:
	db $85, $00, $83, $98, $22
@song0ref967:
	db $85, $00, $83, $22, $85, $00, $83, $29, $85, $00, $83, $22, $85, $00, $83, $2b, $85, $00, $83, $29, $85, $00, $83, $96
	db $26, $85, $00, $83, $1d
	db $ff, $20
	dw @song0ref962
@song0ref999:
	db $85, $00, $83, $20
@song0ref1003:
	db $85, $00, $83, $20, $85, $00, $83, $98, $27, $85, $00, $83, $96, $20, $85, $00, $83, $98, $29, $85, $00, $83, $96, $27
	db $85, $00, $83, $24, $85, $00, $83, $1b
	db $ff, $20
	dw @song0ref999
	db $85, $00, $83
	db $ff, $20
	dw @song0ref772
	db $ff, $0c
	dw @song0ref794
	db $ff, $0c
	dw @song0ref794
	db $98, $2b, $85, $00, $83, $96, $1f, $85, $00, $83
	db $ff, $14
	dw @song0ref645
	db $ff, $0c
	dw @song0ref923
	db $ff, $14
	dw @song0ref646
	db $ff, $0c
	dw @song0ref923
@song0ref1072:
	db $96
@song0ref1073:
	db $20, $85, $00, $83, $20, $85, $00, $83, $98, $24, $85, $00, $83, $96, $20, $85, $00, $83, $26
	db $ff, $0f
	dw @song0ref1003
	db $ff, $11
	dw @song0ref1073
	db $ff, $0f
	dw @song0ref1003
@song0ref1101:
	db $98, $22, $85, $00, $83, $96, $22, $85, $00, $83, $26, $85, $00, $83, $98, $22, $85, $00, $83, $27
	db $ff, $0f
	dw @song0ref967
@song0ref1124:
	db $22, $85, $00, $83, $22, $85, $00, $83, $96, $26, $85, $00, $83, $98, $22, $85, $00, $83, $27
	db $ff, $0f
	dw @song0ref967
	db $96, $2b, $85, $00, $83
@song0ref1151:
	db $26, $85, $00, $83, $1f, $85, $00, $83, $98, $2b, $85, $00, $83, $96
	db $ff, $0c
	dw @song0ref1151
	db $96
	db $ff, $0c
	dw @song0ref772
	db $98, $27, $85, $00, $83, $96
	db $ff, $10
	dw @song0ref827
	db $26, $85, $00, $83
	db $ff, $14
	dw @song0ref645
	db $ff, $0c
	dw @song0ref923
	db $ff, $14
	dw @song0ref646
	db $ff, $0c
	dw @song0ref923
	db $ff, $11
	dw @song0ref1072
	db $ff, $0f
	dw @song0ref1003
	db $ff, $11
	dw @song0ref1073
	db $ff, $0f
	dw @song0ref1003
	db $ff, $11
	dw @song0ref1101
	db $ff, $0f
	dw @song0ref967
	db $ff, $11
	dw @song0ref1124
	db $ff, $0f
	dw @song0ref967
@song0ref1221:
	db $27, $85, $00, $83, $22, $85, $00, $83, $1b, $85, $00, $83
	db $ff, $0c
	dw @song0ref1221
	db $27, $85, $00, $83, $1b, $85, $00, $83, $2b, $85, $00, $83, $96
	db $ff, $0c
	dw @song0ref1151
	db $96
	db $ff, $0c
	dw @song0ref1151
	db $96, $1f, $85, $00, $83
	db $ff, $20
	dw @song0ref645
	db $ff, $20
	dw @song0ref646
	db $ff, $20
	dw @song0ref646
	db $ff, $20
	dw @song0ref646
	db $fd
	dw @song0ch2loop
@song0ch3:
@song0ref1276:
	db $92
@song0ref1277:
	db $2b, $b5, $2b, $b5, $2b, $b5, $2b, $b5, $2b, $b5, $2b, $b5, $2b, $b5, $2b, $b5
@song0ch3loop:
	db $92
@song0ref1295:
	db $2b, $b5, $2b, $b5, $2b, $b5, $2b, $b5, $2b, $b5, $2b, $f7, $ad
	db $ff, $10
	dw @song0ref1277
	db $ff, $10
	dw @song0ref1277
	db $ff, $10
	dw @song0ref1277
	db $ff, $0d
	dw @song0ref1295
	db $ff, $10
	dw @song0ref1277
	db $ff, $10
	dw @song0ref1277
	db $ff, $10
	dw @song0ref1277
	db $ff, $0d
	dw @song0ref1295
@song0ref1332:
	db $2b, $93, $00, $83, $2d, $87, $00, $8f, $2b, $93, $00, $83, $2d, $87, $00, $8f
	db $ff, $10
	dw @song0ref1332
	db $ff, $10
	dw @song0ref1332
	db $ff, $10
	dw @song0ref1332
	db $ff, $10
	dw @song0ref1332
	db $ff, $10
	dw @song0ref1332
	db $ff, $10
	dw @song0ref1332
	db $94, $2d, $2d, $a7, $2d, $a7, $2d, $97, $92
	db $ff, $10
	dw @song0ref1332
	db $ff, $10
	dw @song0ref1332
	db $ff, $10
	dw @song0ref1332
	db $ff, $10
	dw @song0ref1332
	db $ff, $10
	dw @song0ref1332
	db $ff, $10
	dw @song0ref1332
	db $94, $2d, $2d, $a7, $2d, $a7, $2d, $97, $00, $ed, $92
	db $ff, $10
	dw @song0ref1332
	db $ff, $10
	dw @song0ref1332
	db $ff, $10
	dw @song0ref1332
	db $ff, $10
	dw @song0ref1332
	db $ff, $10
	dw @song0ref1332
	db $ff, $10
	dw @song0ref1332
	db $94, $2d, $2d, $a7, $2d, $a7, $2d, $97, $00, $ed
	db $ff, $10
	dw @song0ref1276
	db $fd
	dw @song0ch3loop
@song0ch4:
	db $01, $ed, $01, $ed, $01, $ed, $01, $ed
@song0ch4loop:
	db $01, $ed, $01, $ed, $01, $ed, $01, $8b, $02, $8b, $02, $8b, $02, $8b, $02, $8b, $01, $8b, $02, $8b, $01
@song0ref1468:
	db $8b
@song0ref1469:
	db $01, $99
@song0ref1471:
	db $02, $99
@song0ref1473:
	db $01, $8b, $01, $8b, $02, $99, $01, $8b, $01, $8b, $02, $8b, $01, $99, $01, $8b, $02, $99
	db $ff, $16
	dw @song0ref1469
	db $ff, $16
	dw @song0ref1469
	db $ff, $16
	dw @song0ref1469
	db $ff, $16
	dw @song0ref1469
	db $ff, $16
	dw @song0ref1469
	db $ff, $16
	dw @song0ref1469
@song0ref1509:
	db $01, $99, $02, $8b, $01, $8b, $01, $8b, $01, $8b, $02, $8b, $01, $8b
@song0ref1523:
	db $01, $85, $03, $87, $03
@song0ref1528:
	db $87, $03, $8b, $03, $8b, $04, $8b, $04, $8b, $05, $8b, $05
	db $ff, $17
	dw @song0ref1468
	db $ff, $16
	dw @song0ref1469
	db $ff, $16
	dw @song0ref1469
	db $ff, $16
	dw @song0ref1469
	db $ff, $16
	dw @song0ref1469
	db $ff, $16
	dw @song0ref1469
	db $ff, $16
	dw @song0ref1469
	db $ff, $1f
	dw @song0ref1509
	db $8b
	db $ff, $11
	dw @song0ref1473
	db $8b, $01, $8b, $01, $8b, $01, $8b
	db $ff, $13
	dw @song0ref1471
	db $8b, $01, $8b, $01, $8b, $01, $8b
	db $ff, $13
	dw @song0ref1471
	db $8b, $01, $8b, $01, $8b, $01, $8b
	db $ff, $0f
	dw @song0ref1471
	db $8b, $02, $8b, $01, $8b, $01, $8b, $02, $8b, $01, $8b, $01, $8b, $02, $8b, $01, $8b
	db $ff, $11
	dw @song0ref1473
	db $8b, $01, $8b, $01, $8b, $02, $8b, $02, $8b, $01, $8b
	db $ff, $11
	dw @song0ref1473
	db $8b, $01, $8b, $01, $8b, $02, $8b, $02, $8b, $01, $8b
	db $ff, $11
	dw @song0ref1473
@song0ref1646:
	db $8b, $01, $8b, $01, $8b, $02, $8b, $02, $8b, $01, $8b, $02, $8b, $04, $8b, $05, $8b, $02, $8b, $04, $8b, $05, $8b, $02
	db $8b, $05, $8b, $02, $85, $02, $87, $02
	db $ff, $0c
	dw @song0ref1528
	db $8b
	db $ff, $11
	dw @song0ref1473
	db $8b, $01, $8b, $01, $8b, $02, $8b, $02, $8b, $01, $8b
	db $ff, $11
	dw @song0ref1473
	db $8b, $01, $8b, $01, $8b, $02, $8b, $02, $8b, $01, $8b
	db $ff, $11
	dw @song0ref1473
	db $ff, $20
	dw @song0ref1646
	db $ff, $0c
	dw @song0ref1528
	db $8b, $01, $ed, $01, $ed
	db $ff, $11
	dw @song0ref1523
	db $8b, $01, $8b, $03, $8b, $03, $8b, $03, $8b, $03, $8b, $03, $8b, $04, $99, $fd
	dw @song0ch4loop
