;this file for FamiStudio Sound Engine generated by FamiStudio

music_data:
	db 1
	dw @instruments
	dw @samples-4
	dw @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4
	db <(@tempo_env_10_mid), >(@tempo_env_10_mid), 0, 0

@instruments:
	dw @env3,@env1,@env6,@env5
	dw @env14,@env1,@env2,@env5
	dw @env11,@env1,@env8,@env5
	dw @env7,@env1,@env6,@env5
	dw @env10,@env1,@env6,@env5
	dw @env9,@env1,@env6,@env5
	dw @env12,@env1,@env6,@env5
	dw @env0,@env1,@env6,@env5
	dw @env4,@env1,@env2,@env5
	dw @env13,@env1,@env6,@env5

@samples:
@env0:
	db $04,$ca,$7f,$00,$01
@env1:
	db $c0,$7f,$00,$00
@env2:
	db $c3,$7f,$00,$00
@env3:
	db $04,$cf,$7f,$00,$01
@env4:
	db $00,$c1,$c2,$c3,$c4,$c5,$c6,$c7,$c8,$c9,$ca,$00,$0a
@env5:
	db $00,$c0,$7f,$00,$01
@env6:
	db $7f,$00,$00
@env7:
	db $00,$ca,$c4,$00,$02
@env8:
	db $c1,$7f,$00,$00
@env9:
	db $00,$ca,$02,$c2,$00,$03
@env10:
	db $00,$ca,$02,$c5,$00,$03
@env11:
	db $00,$c7,$06,$c1,$00,$03
@env12:
	db $00,$ca,$02,$c6,$03,$c2,$00,$05
@env13:
	db $04,$c7,$7f,$00,$01
@env14:
	db $00,$c7,$02,$c5,$03,$c1,$00,$05
@env15:
	db $00,$c0,$bd,$bc,$bd,$c0,$c3,$c4,$c3,$00,$01
@env16:
	db $00,$c0,$bf,$be,$bf,$c0,$c1,$c2,$c1,$00,$01
@env17:
	db $00,$c0,$bc,$ba,$bc,$c0,$c4,$c6,$c4,$00,$01
@tempo_env_10_mid:
	db $03,$04,$06,$05,$05,$05,$80
@song0ch0:
	db $f7, $f7, $bb, $6b, $90, $32, $cd, $63, <(@env15), >(@env15), $e1, $00, $63, <(@env5), >(@env5), $64, $37, $a3, $00, $39
	db $a3, $00, $3c, $a3, $00, $6b, $3c, $b7, $00, $3b, $8f, $00, $3b, $b9, $63, <(@env15), >(@env15), $cd, $00, $63, <(@env5)
	db >(@env5), $64, $39, $a3, $00, $37, $a3, $00, $6b, $3e, $f3, $00, $37, $f3, $00, $43, $b9, $6b, $bb, $63, <(@env16), >(@env16)
	db $f7, $b9, $00, $63, <(@env5), >(@env5), $64, $45, $a3, $00, $43, $8f, $00, $6b, $4a, $f7, $a5, $63, <(@env16), >(@env16)
	db $f7, $a5, $63, <(@env5), >(@env5), $64, $00
@song0ch0loop:
	db $6a, <(@tempo_env_10_mid), >(@tempo_env_10_mid), $cf, $8e, $2f, $8f, $00, $30, $8f, $00, $32, $8f, $00, $32, $b7, $00
	db $37, $a3, $00, $36, $a3, $00, $37, $a3, $00, $6b, $39, $a3, $00, $3b, $8f, $00, $37, $cd, $63, <(@env17), >(@env17), $f7
	db $91, $00, $63, <(@env5), >(@env5), $64, $36, $8f, $00, $37, $8f, $00, $6b, $3e, $b7, $00, $37, $8f, $00, $37, $cd, $63
	db <(@env17), >(@env17), $f7, $63, <(@env5), >(@env5), $64, $91, $00, $37, $8f, $00, $6b, $37, $cb, $00, $93, $39, $8f, $00
	db $37, $8f, $00, $36, $cd, $63, <(@env17), >(@env17), $e1, $00, $6b, $63, <(@env5), >(@env5), $64, $2f, $cb, $00, $93, $2d
	db $8f, $00, $2b, $8f, $00, $32, $cb, $00, $93, $37, $a3, $00, $39, $a3, $00, $6b, $3c, $b7, $00, $3b, $8f, $00, $3b, $cd
	db $63, <(@env17), >(@env17), $cd, $00, $63, <(@env5), >(@env5), $64, $3e, $a3, $00, $3c, $a3, $00, $6b, $3b, $8f, $00, $3c
	db $8f, $00, $3b, $8f, $00, $37, $a3, $00, $32, $cb, $00, $39, $8f, $00, $37, $8f, $00, $36, $8f, $00, $34, $8f, $00, $36
	db $b7, $00, $6b, $37, $8f, $00, $a7, $37, $8f, $00, $a7, $37, $a3, $00, $8d, $72, $61, $f8, $23, $32, $8d, $73, $8f, $75
	db $8f, $76, $8f, $77, $8f, $79, $8f, $7a, $8f, $7c, $8f, $7e, $8f, $00, $6b, $7f
@song0ref301:
	db $37, $8f, $00, $37, $8f, $00, $a7, $39, $8f, $00, $39, $8f, $00, $93, $35, $cb, $00, $32, $a3, $00, $35, $8f, $00, $30
	db $83, $31, $83, $00, $30, $81, $00, $2e, $8f, $00, $6b, $30, $a3, $00, $2e, $8f, $00, $30, $8f, $00, $93, $2e, $8f, $00
	db $93, $32, $f7, $a3, $00, $93, $6b
	db $ff, $0e
	dw @song0ref301
	db $3a, $a3, $00, $35, $a3, $00, $35, $a3, $00, $35, $8f, $00, $3a, $8f, $00, $3c, $91, $6b, $f5, $00, $3a, $8f, $00, $3e
	db $f3, $00, $3e, $8f, $00, $3e, $8f, $00, $3e, $91, $6b, $cf, $63, <(@env17), >(@env17), $f7, $a5, $00, $63, <(@env5), >(@env5)
	db $64, $1b, $a3, $00, $1d, $a3, $00, $fd
	dw @song0ch0loop
@song0ch1:
	db $84
@song0ref415:
	db $37, $8f, $00, $3e, $8f, $00, $43, $8f, $00, $45, $8f, $00, $3e, $8f, $00, $43, $8f, $00, $45
@song0ref434:
	db $8f, $00, $48, $8f, $00, $3e, $8f, $00, $48, $8f, $00, $47, $8f, $00, $3e, $8f, $00, $47, $8f, $00, $45, $8f, $00, $43
	db $8f, $00
	db $ff, $2d
	dw @song0ref415
	db $ff, $2d
	dw @song0ref415
	db $ff, $2d
	dw @song0ref415
	db $ff, $2d
	dw @song0ref415
	db $82
	db $ff, $15
	dw @song0ref415
	db $3e
	db $ff, $1a
	dw @song0ref434
@song0ch1loop:
	db $82
	db $ff, $15
	dw @song0ref415
	db $3e
	db $ff, $1a
	dw @song0ref434
	db $ff, $15
	dw @song0ref415
	db $3e
	db $ff, $1a
	dw @song0ref434
	db $ff, $15
	dw @song0ref415
	db $3e
	db $ff, $1a
	dw @song0ref434
	db $ff, $15
	dw @song0ref415
	db $3e
	db $ff, $1a
	dw @song0ref434
	db $ff, $15
	dw @song0ref415
	db $3e
	db $ff, $1a
	dw @song0ref434
	db $ff, $15
	dw @song0ref415
	db $3e
	db $ff, $1a
	dw @song0ref434
	db $ff, $15
	dw @song0ref415
	db $3e
	db $ff, $1a
	dw @song0ref434
	db $43, $8f, $00, $3a, $8f, $00, $3f, $8f, $00, $45, $8f, $00, $3c, $8f, $00, $45, $8f, $00, $48, $8f, $00, $47, $8f, $00
	db $43, $8f, $00, $3e, $8f, $00, $3c, $8f, $00, $3b, $8f, $00, $37, $8f, $00, $32, $8f, $00, $30, $8f, $00, $2f, $8f, $00
	db $92, $2e, $8f, $00, $2e, $8f, $00, $a7, $30, $8f, $00, $30, $8f, $00, $93, $2e, $a3, $00, $84, $39, $8f, $00, $3a, $8f
	db $00, $41, $8f, $00, $93, $45, $8f, $00, $46, $8f, $00, $4d, $8f, $00, $92, $27, $a3, $00, $27, $8f, $00, $27, $8f, $00
	db $93, $27, $8f, $00, $93, $2a, $f7, $a3, $00, $93, $33, $8f, $00, $33, $8f, $00, $a7, $30, $8f, $00, $30, $8f, $00, $93
	db $32, $a3, $00, $32, $a3, $00, $32, $a3, $00, $32, $8f, $00, $35, $8f, $00, $37, $91, $e1, $00, $93, $37, $8f, $00, $36
	db $f3, $00, $36, $8f, $00, $36, $8f, $00, $37, $8f, $00, $82
	db $ff, $15
	dw @song0ref415
	db $3e
	db $ff, $1a
	dw @song0ref434
	db $fd
	dw @song0ch1loop
@song0ch2:
	db $f7, $f7, $bb, $80, $2b, $b7, $00, $32, $b7, $00, $37, $f7, $a3, $00, $93, $29, $b7, $00, $30, $b7, $00, $35, $f7, $a3
	db $00, $93, $28, $b7, $00, $2f, $b7, $00, $34, $f7, $a3, $00, $93, $27, $b7, $00, $2e, $b7, $00, $33, $f7, $a3, $00, $93
@song0ref745:
	db $37, $8f, $00, $37, $8f, $00, $37, $8f, $00, $37, $8f, $00
	db $ff, $0c
	dw @song0ref745
	db $ff, $0c
	dw @song0ref745
	db $ff, $0c
	dw @song0ref745
@song0ch2loop:
	db $80
	db $ff, $0c
	dw @song0ref745
	db $ff, $0c
	dw @song0ref745
@song0ref774:
	db $36, $8f, $00, $36, $8f, $00, $36, $8f, $00, $36, $8f, $00
	db $ff, $0c
	dw @song0ref774
@song0ref789:
	db $34, $8f, $00, $34, $8f, $00, $34, $8f, $00, $34, $8f, $00
	db $ff, $0c
	dw @song0ref789
@song0ref804:
	db $32, $8f, $00, $32, $8f, $00, $32, $8f, $00, $32, $8f, $00
	db $ff, $0c
	dw @song0ref804
@song0ref819:
	db $30, $8f, $00, $30, $8f, $00, $30, $8f, $00, $30, $8f, $00
	db $ff, $0c
	dw @song0ref819
@song0ref834:
	db $31, $8f, $00, $31, $8f, $00, $31, $8f, $00, $31, $8f, $00
	db $ff, $0c
	dw @song0ref834
	db $ff, $0c
	dw @song0ref804
	db $ff, $0c
	dw @song0ref804
	db $ff, $0c
	dw @song0ref804
	db $ff, $0c
	dw @song0ref804
	db $ff, $0c
	dw @song0ref745
	db $ff, $0c
	dw @song0ref745
@song0ref867:
	db $35, $8f, $00, $35, $8f, $00, $35, $8f, $00, $35, $8f, $00
	db $ff, $0c
	dw @song0ref867
	db $ff, $0c
	dw @song0ref789
	db $ff, $0c
	dw @song0ref789
@song0ref888:
	db $33, $8f, $00, $33, $8f, $00, $33, $8f, $00, $33, $8f, $00
	db $ff, $0c
	dw @song0ref888
	db $ff, $0c
	dw @song0ref804
	db $ff, $0c
	dw @song0ref804
	db $ff, $0c
	dw @song0ref834
	db $ff, $0c
	dw @song0ref804
	db $33, $8f, $00, $a7, $35, $8f, $00, $a7, $37, $b7, $00, $2b, $8f, $00, $2b, $8f, $00, $2b, $8f, $00, $2b, $8f, $00, $2b
	db $8f, $00, $2b, $8f, $00, $2b, $8f, $00
@song0ref947:
	db $30, $8f, $00, $30, $8f, $00, $a7, $35, $8f, $00, $35, $8f, $00, $93, $2e, $a3, $00, $2e, $8f, $00, $2e, $8f, $00, $2e
	db $8f, $00, $2e, $8f, $00, $2e, $8f, $00, $2e, $8f, $00, $2e, $8f, $00
	db $ff, $0c
	dw @song0ref819
	db $ff, $0c
	dw @song0ref819
	db $ff, $0c
	dw @song0ref804
	db $ff, $0c
	dw @song0ref804
	db $ff, $26
	dw @song0ref947
	db $ff, $0c
	dw @song0ref819
	db $ff, $0c
	dw @song0ref819
	db $ff, $0c
	dw @song0ref804
	db $ff, $0c
	dw @song0ref804
	db $ff, $0c
	dw @song0ref888
	db $ff, $0c
	dw @song0ref888
	db $33, $8f, $00, $bb, $33, $a3, $00, $35, $a3, $00, $fd
	dw @song0ch2loop
@song0ch3:
@song0ref1031:
	db $f7, $f7, $bb, $f7, $f7, $bb, $f7, $f7, $bb, $f7, $f7, $bb, $f7, $e3, $88, $25, $8b, $00, $83, $20, $8b, $00, $83, $25
	db $8b, $00, $83, $20, $8b, $00, $83
@song0ref1062:
	db $8a, $20, $8b, $00, $83, $86, $2c, $83, $00, $8b, $8c, $25, $8f, $00, $86, $2c, $83, $00, $8b
	db $ff, $0f
	dw @song0ref1062
	db $ff, $0f
	dw @song0ref1062
@song0ref1087:
	db $8a, $20, $8b, $00, $83, $86, $2c, $83, $00, $8b, $8c, $25, $8f, $00, $25, $8f, $00
@song0ch3loop:
	db $ff, $0f
	dw @song0ref1062
	db $ff, $0f
	dw @song0ref1062
	db $ff, $0f
	dw @song0ref1062
	db $ff, $0e
	dw @song0ref1087
	db $ff, $0f
	dw @song0ref1062
	db $ff, $0f
	dw @song0ref1062
	db $ff, $0f
	dw @song0ref1062
	db $ff, $0e
	dw @song0ref1087
	db $ff, $0f
	dw @song0ref1062
	db $ff, $0f
	dw @song0ref1062
	db $ff, $0f
	dw @song0ref1062
	db $ff, $0e
	dw @song0ref1087
	db $ff, $0f
	dw @song0ref1062
	db $ff, $0f
	dw @song0ref1062
	db $ff, $0f
	dw @song0ref1062
	db $ff, $0e
	dw @song0ref1087
	db $ff, $0f
	dw @song0ref1062
	db $ff, $0f
	dw @song0ref1062
	db $ff, $0f
	dw @song0ref1062
	db $ff, $0e
	dw @song0ref1087
	db $ff, $0f
	dw @song0ref1062
	db $ff, $0f
	dw @song0ref1062
	db $ff, $0f
	dw @song0ref1062
	db $ff, $0e
	dw @song0ref1087
	db $ff, $0f
	dw @song0ref1062
	db $ff, $0f
	dw @song0ref1062
	db $ff, $0f
	dw @song0ref1062
	db $ff, $0e
	dw @song0ref1087
	db $ff, $0f
	dw @song0ref1062
	db $ff, $0f
	dw @song0ref1062
	db $ff, $0f
	dw @song0ref1062
	db $ff, $0e
	dw @song0ref1087
	db $ff, $0f
	dw @song0ref1062
	db $ff, $0f
	dw @song0ref1062
	db $ff, $0f
	dw @song0ref1062
	db $ff, $0e
	dw @song0ref1087
	db $ff, $0f
	dw @song0ref1062
	db $ff, $0f
	dw @song0ref1062
	db $ff, $0f
	dw @song0ref1062
	db $ff, $0e
	dw @song0ref1087
	db $ff, $0f
	dw @song0ref1062
	db $ff, $0f
	dw @song0ref1062
	db $ff, $0f
	dw @song0ref1062
	db $ff, $0e
	dw @song0ref1087
	db $ff, $0f
	dw @song0ref1062
	db $ff, $0f
	dw @song0ref1062
	db $ff, $0f
	dw @song0ref1062
	db $ff, $0e
	dw @song0ref1087
	db $ff, $0f
	dw @song0ref1062
	db $ff, $0f
	dw @song0ref1062
	db $ff, $0f
	dw @song0ref1062
	db $ff, $0e
	dw @song0ref1087
	db $fd
	dw @song0ch3loop
@song0ch4:
	db $ff, $0d
	dw @song0ref1031
	db $f7, $bb, $f7, $f7, $cf
@song0ch4loop:
@song0ref1273:
	db $f7, $f7, $cf, $f7, $f7, $cf, $f7, $f7, $cf, $f7, $f7, $cf
	db $ff, $0c
	dw @song0ref1273
	db $ff, $0c
	dw @song0ref1273
	db $f7, $f7, $cf, $fd
	dw @song0ch4loop
