;this file for FamiStudio Sound Engine generated by FamiStudio

music_data:
	db 1
	dw @instruments
	dw @samples-4
	dw @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4
	db <(@tempo_env_12_mid), >(@tempo_env_12_mid), 0, 0

@instruments:
	dw @env3,@env0,@env6,@env4
	dw @env3,@env0,@env6,@env7
	dw @env9,@env0,@env6,@env7
	dw @env8,@env0,@env5,@env4
	dw @env10,@env0,@env5,@env4
	dw @env10,@env0,@env5,@env1
	dw @env2,@env0,@env5,@env4
	dw @env2,@env0,@env5,@env1

@samples:
	db $00+<(FAMISTUDIO_DPCM_PTR),$10,$0f,$40	;1 (NG Bass Drum)
	db $04+<(FAMISTUDIO_DPCM_PTR),$20,$0f,$40	;2 (NG Snare)

@env0:
	db $c0,$7f,$00,$00
@env1:
	db $00,$c1,$7f,$00,$01
@env2:
	db $04,$cf,$7f,$00,$01
@env3:
	db $00,$c4,$05,$c3,$06,$c2,$07,$c1,$00,$07
@env4:
	db $00,$c0,$7f,$00,$01
@env5:
	db $7f,$00,$00
@env6:
	db $c1,$7f,$00,$00
@env7:
	db $00,$c1,$bf,$be,$bf,$c1,$c2,$c3,$c2,$00,$01
@env8:
	db $00,$c9,$c7,$c5,$c3,$c1,$c0,$00,$06
@env9:
	db $04,$c4,$7f,$00,$01
@env10:
	db $00,$c5,$c5,$c4,$c4,$c3,$c3,$c2,$c2,$c1,$00,$09
@tempo_env_12_mid:
	db $03,$05,$05,$80
@song0ch0:
	db $f7, $c7
@song0ch0loop:
	db $6a, <(@tempo_env_12_mid), >(@tempo_env_12_mid), $82
@song0ref8:
	db $2b, $95, $2e, $95, $80, $2b, $95, $82, $30, $95, $29, $89, $2b, $95, $29, $89, $2b, $95, $32, $95, $6b, $84, $2b, $c5
	db $82, $2d, $95, $80, $2e, $95, $82, $2d, $95, $2b, $ad, $6b, $2d, $95, $2b, $95, $30, $95, $2d, $95, $2b, $89, $2d, $95
	db $2b, $89, $2d, $95, $32, $95, $6b, $84, $2d, $c5, $80, $2e, $95, $30, $95, $2e, $95, $82, $2d, $ad, $6b
	db $ff, $38
	dw @song0ref8
	db $6b, $2b, $ad, $29, $ad, $27, $ad, $26, $ad, $6b, $00, $95, $26, $95, $26, $95, $26, $ad
@song0ref98:
	db $26, $95, $2b, $95, $2d, $95, $6b, $80, $2e, $95, $2d, $95, $2e, $95, $82, $2b, $ad, $32, $95, $30, $95, $2e, $95, $6b
	db $80, $30, $95, $2e, $95, $30, $95, $82, $2b, $ad, $80, $2e, $95, $82, $2d, $95, $2b, $95, $6b, $29, $95, $2b, $95, $2d
	db $95, $35, $ad, $33, $95, $32, $95, $30, $95, $6b, $32, $b9, $00, $b9
	db $ff, $34
	dw @song0ref98
	db $26, $89, $29, $89, $2b, $89, $2d, $89, $80, $2e, $89, $82, $30, $89
@song0ref177:
	db $6b, $80, $2e, $95, $82, $2d, $89, $80, $2e, $95, $82, $2b, $89, $80, $2e, $95, $82, $2d, $89, $80, $2e, $95, $82, $2b
	db $89, $30, $89, $80, $2e, $89, $2d, $89, $2e, $89, $6b, $97, $2d, $89, $2e, $95, $2b, $89, $2e, $95, $2d, $89, $2e, $95
	db $2b, $89, $30, $89, $2e, $89, $2d, $89, $2b, $89, $6b, $30, $95, $2e, $89, $30, $95, $2d, $89, $30, $95, $2e, $89, $30
	db $95, $2d, $89, $32, $89, $30, $89, $2e, $89, $2d, $89, $6b, $82, $2b, $89, $29, $89, $26, $89, $27, $89, $2b, $89, $26
	db $89, $29, $89, $2b, $89, $2e, $89, $2d, $89, $2b, $89, $29, $89, $32, $95, $30, $95
	db $ff, $63
	dw @song0ref177
	db $fd
	dw @song0ch0loop
@song0ch1:
	db $f7, $c7
@song0ch1loop:
@song0ref299:
	db $88, $1f, $91, $00, $81, $8a, $2b, $89, $88, $26, $89, $00, $89, $26, $89, $8a, $2b, $91, $00, $81, $88, $1f, $89, $8a
	db $2b, $89, $88, $26, $91, $00, $81, $8a, $2b, $91, $00, $81, $88, $26, $91, $00, $81, $1b, $91, $00, $81, $8a, $2b, $89
	db $88, $27, $89, $00, $89, $27, $89, $8a, $2b, $91, $00, $81, $88, $1b, $89, $8a, $2b, $89, $88, $27, $91, $00, $81, $8a
	db $2b, $91, $00, $81, $88, $27, $91, $00, $81, $1d, $91, $00, $81, $8a, $2b, $89, $29, $89, $00, $89, $29, $89, $2b, $91
	db $00, $81, $88, $1d, $89, $8a, $2b, $89, $29, $91, $00, $81, $2b, $91, $00, $81, $29, $91, $00, $81, $1a, $91, $00, $81
	db $2b, $89, $88, $26, $89, $8a, $2b, $89, $00, $89, $2b, $a9, $00, $81, $2b, $91, $00, $81, $2a, $91, $00, $99
	db $ff, $78
	dw @song0ref299
	db $1a, $91, $00, $81, $2b, $89, $88, $26, $89, $1d, $91, $00, $81, $8a, $29, $89, $88, $24, $89, $1b, $91, $00, $81, $27
	db $89, $8a, $22, $89, $88, $1a, $91, $00, $81, $1a, $89, $21, $89, $8a, $1a, $91, $00, $81, $1a, $91, $00, $81, $1a, $91
	db $00, $81, $1a, $91, $00, $81, $1a, $91, $00, $c9
	db $ff, $6d
	dw @song0ref299
@song0ref505:
	db $89, $2b, $89, $2e, $91, $00, $81, $2d, $91, $00, $81, $2b, $91, $00, $99
	db $ff, $6d
	dw @song0ref299
	db $ff, $0f
	dw @song0ref505
	db $ff, $6d
	dw @song0ref299
	db $ff, $0f
	dw @song0ref505
	db $ff, $6d
	dw @song0ref299
	db $ff, $0f
	dw @song0ref505
	db $fd
	dw @song0ch1loop
@song0ch2:
@song0ref541:
	db $8e
@song0ref542:
	db $1a, $89, $00, $89, $8c, $26, $89, $00, $89, $8e, $1a, $89, $00, $89, $8c, $26, $89, $00, $89
	db $ff, $10
	dw @song0ref541
@song0ch2loop:
@song0ref565:
	db $8c
@song0ref566:
	db $1f, $89, $00, $89, $8e, $2b, $89, $00, $89, $8c, $1f, $89, $00, $89, $8e, $2b, $89, $00, $89
	db $ff, $10
	dw @song0ref565
@song0ref588:
	db $8c
@song0ref589:
	db $1b, $89, $00, $89, $27, $89, $00, $89, $1b, $89, $00, $89, $27, $89, $00, $89
	db $ff, $10
	dw @song0ref589
@song0ref608:
	db $1d, $89, $00, $89, $8e, $29, $89, $00, $89, $8c, $1d, $89, $00, $89, $8e, $29, $89, $00, $89, $8c
	db $ff, $10
	dw @song0ref608
	db $ff, $10
	dw @song0ref542
@song0ref634:
	db $8e, $1a, $89, $00, $89, $8c, $26, $89, $00, $89, $1d, $89, $00, $89, $1e, $89, $00, $89
	db $ff, $10
	dw @song0ref566
	db $ff, $10
	dw @song0ref565
	db $ff, $10
	dw @song0ref588
	db $ff, $10
	dw @song0ref589
	db $ff, $10
	dw @song0ref608
	db $8c
	db $ff, $10
	dw @song0ref608
	db $ff, $10
	dw @song0ref542
	db $ff, $10
	dw @song0ref634
	db $1f, $89, $00, $89, $8e, $2b, $89, $00, $89, $8c, $1d, $89, $00, $89, $8e, $29, $89, $00, $89, $8c, $1b, $89, $00, $89
	db $27, $89, $00, $89, $8e, $1a, $89, $00, $89, $8c, $26, $89, $00, $89, $8e, $1a, $89, $00, $89, $1a, $89, $00, $89, $1a
	db $89, $00, $89, $1a, $89, $00, $89, $1a, $89, $00, $d1
	db $ff, $10
	dw @song0ref565
	db $ff, $10
	dw @song0ref565
	db $ff, $10
	dw @song0ref588
	db $ff, $10
	dw @song0ref589
	db $ff, $10
	dw @song0ref608
	db $8c
	db $ff, $10
	dw @song0ref608
	db $ff, $10
	dw @song0ref542
	db $ff, $10
	dw @song0ref634
	db $ff, $10
	dw @song0ref566
	db $ff, $10
	dw @song0ref565
	db $ff, $10
	dw @song0ref588
	db $ff, $10
	dw @song0ref589
	db $ff, $10
	dw @song0ref608
	db $8c
	db $ff, $10
	dw @song0ref608
	db $ff, $10
	dw @song0ref542
	db $ff, $10
	dw @song0ref634
	db $ff, $10
	dw @song0ref566
	db $ff, $10
	dw @song0ref565
	db $ff, $10
	dw @song0ref588
	db $ff, $10
	dw @song0ref589
	db $ff, $10
	dw @song0ref608
	db $8c
	db $ff, $10
	dw @song0ref608
	db $ff, $10
	dw @song0ref542
	db $ff, $10
	dw @song0ref634
	db $ff, $10
	dw @song0ref566
	db $ff, $10
	dw @song0ref565
	db $ff, $10
	dw @song0ref588
	db $ff, $10
	dw @song0ref589
	db $ff, $10
	dw @song0ref608
	db $8c
	db $ff, $10
	dw @song0ref608
	db $ff, $10
	dw @song0ref542
	db $ff, $10
	dw @song0ref634
	db $fd
	dw @song0ch2loop
@song0ch3:
@song0ref839:
	db $86
@song0ref840:
	db $2e
@song0ref841:
	db $95, $2e, $89, $2e, $89
@song0ref846:
	db $2e, $89, $2e
@song0ref849:
	db $89
@song0ref850:
	db $2e, $89, $2e, $89, $2e, $95, $2e, $89, $2e, $89, $2e, $89, $2e, $95, $2e, $89
@song0ch3loop:
	db $ff, $1a
	dw @song0ref839
	db $ff, $0f
	dw @song0ref846
	db $ff, $16
	dw @song0ref841
	db $ff, $11
	dw @song0ref849
	db $ff, $0f
	dw @song0ref846
	db $ff, $16
	dw @song0ref841
	db $ff, $11
	dw @song0ref849
	db $ff, $0f
	dw @song0ref846
	db $ff, $16
	dw @song0ref841
	db $ff, $11
	dw @song0ref849
	db $ff, $0f
	dw @song0ref846
	db $ff, $14
	dw @song0ref841
	db $95, $2e, $89, $2e, $89, $2e, $95, $2e, $89, $2e, $89, $2e, $95, $2e, $89, $2e, $89, $f7, $97, $2e, $95
	db $ff, $0d
	dw @song0ref850
	db $ff, $11
	dw @song0ref849
	db $ff, $1a
	dw @song0ref840
	db $ff, $1a
	dw @song0ref840
	db $ff, $1a
	dw @song0ref840
	db $ff, $1a
	dw @song0ref840
	db $ff, $1a
	dw @song0ref840
	db $ff, $1a
	dw @song0ref840
	db $ff, $1a
	dw @song0ref840
	db $ff, $1a
	dw @song0ref840
	db $ff, $1a
	dw @song0ref840
	db $ff, $1a
	dw @song0ref840
	db $ff, $1a
	dw @song0ref840
	db $ff, $1a
	dw @song0ref840
	db $ff, $1a
	dw @song0ref840
	db $ff, $1a
	dw @song0ref840
	db $ff, $1a
	dw @song0ref840
	db $fd
	dw @song0ch3loop
@song0ch4:
	db $01, $ad, $02, $ad, $01, $ad, $02, $ad
@song0ch4loop:
@song0ref987:
	db $01, $ad, $02, $ad, $01, $ad, $02, $ad, $01, $ad, $02, $ad, $01, $ad, $02, $ad, $01, $ad, $02, $ad, $01, $ad, $02, $ad
	db $01, $ad, $02, $ad, $02, $89, $02, $95, $02, $89, $02, $89, $02, $89, $02, $89, $02, $89
	db $ff, $2a
	dw @song0ref987
	db $01, $ad, $02, $ad, $01, $ad, $02, $ad, $02, $95, $02, $95, $02, $95, $02, $95, $02, $ad, $02, $95, $02, $89, $02, $89
	db $ff, $1d
	dw @song0ref987
@song0ref1059:
	db $95, $02, $89, $02, $89, $02, $89, $02, $89, $02, $89, $02, $89
	db $ff, $1d
	dw @song0ref987
	db $ff, $0d
	dw @song0ref1059
	db $ff, $1d
	dw @song0ref987
	db $ff, $0d
	dw @song0ref1059
	db $ff, $1d
	dw @song0ref987
	db $ff, $0d
	dw @song0ref1059
	db $fd
	dw @song0ch4loop
