;this file for FamiStudio Sound Engine generated by FamiStudio

music_data:
	db 1
	dw @instruments
	dw @samples-4
	dw @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4
	db <(@tempo_env_7_mid), >(@tempo_env_7_mid), 0, 0

@instruments:
	dw @env4,@env0,@env18,@env15
	dw @env23,@env0,@env3,@env15
	dw @env13,@env0,@env1,@env15
	dw @env27,@env7,@env18,@env15
	dw @env9,@env0,@env1,@env15
	dw @env19,@env0,@env22,@env12
	dw @env8,@env7,@env28,@env15
	dw @env6,@env0,@env2,@env12
	dw @env17,@env0,@env3,@env15
	dw @env17,@env0,@env1,@env15
	dw @env25,@env20,@env18,@env15
	dw @env5,@env16,@env18,@env15
	dw @env14,@env0,@env21,@env15
	dw @env26,@env0,@env18,@env15
	dw @env11,@env0,@env18,@env15
	dw @env24,@env0,@env21,@env15
	dw @env10,@env0,@env18,@env12

@samples:
	db $00+<(FAMISTUDIO_DPCM_PTR),$0b,$0f,$40	;1 (BassDrum)
	db $03+<(FAMISTUDIO_DPCM_PTR),$17,$0e,$40	;2 (Snare)

@env0:
	db $c0,$7f,$00,$00
@env1:
	db $c1,$c0,$00,$01
@env2:
	db $c2,$c1,$00,$01
@env3:
	db $c2,$c0,$00,$01
@env4:
	db $04,$cf,$7f,$00,$01
@env5:
	db $00,$c6,$c2,$c3,$c1,$00,$04
@env6:
	db $00,$c8,$c6,$c5,$03,$c4,$04,$c3,$c3,$c5,$c5,$c4,$c4,$c2,$00,$0d
@env7:
	db $b4,$c0,$00,$01
@env8:
	db $0b,$c8,$c8,$c6,$c5,$03,$c4,$02,$c3,$00,$08,$c2,$00,$0b
@env9:
	db $00,$c6,$c5,$c4,$03,$c3,$00,$05
@env10:
	db $08,$c7,$c8,$c7,$c6,$c5,$00,$05,$c2,$00,$08
@env11:
	db $06,$c3,$c2,$c1,$00,$03,$c2,$00,$06
@env12:
	db $00,$c0,$0b,$c0,$c0,$c1,$c1,$c0,$c0,$bf,$bf,$00,$03
@env13:
	db $00,$c8,$c7,$c6,$c6,$c5,$c5,$c4,$00,$07
@env14:
	db $0c,$c2,$03,$c3,$03,$c4,$03,$c5,$c5,$c6,$00,$09,$c5,$c5,$c4,$00,$0e
@env15:
	db $00,$c0,$7f,$00,$01
@env16:
	db $c0,$c1,$c4,$00,$02
@env17:
	db $08,$c8,$c7,$c6,$c6,$c5,$00,$05,$c2,$00,$08
@env18:
	db $7f,$00,$00
@env19:
	db $09,$c4,$c5,$03,$c4,$0e,$c3,$00,$06,$c2,$00,$09
@env20:
	db $c0,$c8,$ca,$cb,$ca,$cb,$cc,$ce,$00,$07
@env21:
	db $c1,$7f,$00,$00
@env22:
	db $c0,$c1,$00,$01
@env23:
	db $00,$c7,$c6,$c5,$c5,$c4,$c4,$c3,$00,$07
@env24:
	db $00,$c4,$c5,$03,$c4,$00,$04
@env25:
	db $00,$ce,$c8,$c3,$c4,$c3,$c1,$00,$06
@env26:
	db $09,$c4,$c5,$c6,$c7,$c7,$c8,$00,$06,$c2,$00,$09
@env27:
	db $00,$c6,$c6,$c5,$c4,$c4,$c3,$c2,$00,$07
@env28:
	db $c2,$c2,$c1,$00,$02
@tempo_env_7_mid:
	db $03,$05,$05,$06,$03,$06,$05,$05,$80
@song0ch0:
@song0ref1:
	db $86
@song0ref2:
	db $2f, $8b, $2a, $8b, $36, $8b, $2a, $8b
@song0ref10:
	db $34, $8b, $2a, $8b, $32
@song0ref15:
	db $8b, $2a, $8b, $31, $8b, $2a, $8b, $32, $8b, $2a, $8b, $31, $8b, $2a, $8b, $2f
	db $ff, $0b
	dw @song0ref15
	db $ff, $0c
	dw @song0ref10
@song0ref37:
	db $2d, $8b, $2a, $8b, $31, $8b, $2a, $8b, $2f, $8b, $2a, $8b, $6b
	db $ff, $1d
	dw @song0ref2
	db $ff, $0b
	dw @song0ref15
	db $ff, $0c
	dw @song0ref10
	db $ff, $0c
	dw @song0ref37
@song0ch0loop:
	db $6a, <(@tempo_env_7_mid), >(@tempo_env_7_mid)
@song0ref66:
	db $8a
@song0ref67:
	db $31, $8f, $f9, $87, $34, $87, $f9, $81, $32, $8f, $f9, $87, $8c, $25, $89, $f9, $23, $89, $f9, $25, $89, $f9, $26, $91
	db $f9, $85, $28, $91, $f9, $85, $8e, $2a, $b5, $8a, $31, $97, $f9, $8d, $36, $97, $f9, $8d, $32, $af, $f9, $9f, $31, $8f
	db $f9, $87, $2f, $8f, $f9, $87, $6b
	db $ff, $0c
	dw @song0ref67
@song0ref125:
	db $8c, $28, $89, $f9, $26, $89, $f9, $28, $89, $f9, $2a, $91, $f9, $85, $2b, $91, $f9, $85, $2d, $91, $f9, $85, $2f, $91
	db $f9, $85, $98, $31, $95, $f9, $9c, $31, $8d, $98, $31, $9d, $f9, $87, $9c, $31, $99, $98, $2f, $97, $9c, $2f, $8d, $98
	db $2f, $9d, $f9, $87, $9c, $2f, $99, $6b
	db $ff, $33
	dw @song0ref66
	db $6b
	db $ff, $0c
	dw @song0ref67
	db $ff, $24
	dw @song0ref125
	db $9e, $2e, $8f, $9c, $2e, $87, $9e, $2f, $8f, $9c, $2f, $87, $9e, $31, $8f, $9c, $31, $87, $9e, $34, $8f, $9c, $34, $87
	db $6b, $7f, $a0, $28, $89, $f9, $78, $28, $8d, $7f
@song0ref225:
	db $9c, $28, $87, $f9, $7c
@song0ref230:
	db $a0, $26, $8b, $9a, $26, $8f, $f9, $87, $a0, $32, $8b, $9a, $32, $85, $f9, $83, $7f, $a0, $28, $89, $f9, $9a, $28, $8d
	db $ff, $12
	dw @song0ref225
	db $78, $28, $8d, $7f, $9c, $28, $87, $f9
	db $ff, $0c
	dw @song0ref230
	db $82, $26, $8b, $32, $8b, $25, $8b, $31, $8b, $23, $8b, $2f, $8b, $21, $8b, $2d, $8b, $6b, $a0
@song0ref287:
	db $28, $89, $f9, $7d, $28, $8b, $62, $26, $26, $89, $62, $32, $32, $89, $7c, $87, $7d, $87, $7e, $87, $7f, $8d, $f9, $8f
	db $ff, $11
	dw @song0ref287
	db $ff, $11
	dw @song0ref287
	db $90, $32, $93, $f9, $83, $34, $93, $f9, $83, $31, $89, $f9, $32, $9d, $f9, $87, $6b
	db $ff, $1d
	dw @song0ref1
	db $ff, $0b
	dw @song0ref15
	db $ff, $0c
	dw @song0ref10
	db $ff, $0c
	dw @song0ref37
	db $6b
	db $ff, $1d
	dw @song0ref2
	db $ff, $0b
	dw @song0ref15
	db $ff, $0c
	dw @song0ref10
	db $ff, $0c
	dw @song0ref37
	db $fd
	dw @song0ch0loop
@song0ch1:
@song0ref362:
	db $68, $01, $88
@song0ref365:
	db $3b, $8b, $36, $8b, $42, $8b, $36, $8b
@song0ref373:
	db $40, $8b, $36, $8b, $3e
@song0ref378:
	db $8b, $36, $8b, $3d, $8b, $36, $8b, $3e, $8b, $36, $8b, $3d, $8b, $36, $8b, $3b
	db $ff, $0b
	dw @song0ref378
	db $ff, $0c
	dw @song0ref373
@song0ref400:
	db $39, $8b, $36, $8b, $3d, $8b, $36, $8b, $3b, $8b, $36, $8b, $68, $01
	db $ff, $1d
	dw @song0ref365
	db $ff, $0b
	dw @song0ref378
	db $ff, $0c
	dw @song0ref373
	db $ff, $0c
	dw @song0ref400
@song0ch1loop:
@song0ref427:
	db $68, $00, $8a, $34
@song0ref431:
	db $8f, $f9, $87, $39, $87, $f9, $81, $36, $c7, $f9, $b1
@song0ref442:
	db $34, $8f, $f9, $87, $32, $8f, $f9, $87, $34, $97, $f9, $8d, $39, $97, $f9, $8d, $36, $af, $f9, $9f
	db $ff, $09
	dw @song0ref442
	db $ff, $0f
	dw @song0ref431
@song0ref468:
	db $36, $8f, $f9, $87, $98, $37, $95, $f9, $9c, $37, $8d, $98, $39, $9d, $f9, $87, $9c, $39, $99, $98, $36, $97, $9c, $36
	db $8d, $98, $37, $9d, $f9, $87, $9c, $37, $99
	db $ff, $20
	dw @song0ref427
	db $ff, $09
	dw @song0ref442
	db $ff, $0f
	dw @song0ref431
	db $ff, $0f
	dw @song0ref468
	db $9e, $36, $8f, $9c, $36, $87, $9e, $38, $8f, $9c, $38, $87, $9e, $3a, $8f, $9c, $3a, $87, $9e, $3d, $8f, $9c, $3d, $87
	db $7f, $a0, $31, $89, $f9, $78, $31, $8d, $7f
@song0ref546:
	db $9c, $31, $87, $f9, $7c
@song0ref551:
	db $a0, $2f, $8b, $9a, $2f, $8f, $f9, $87, $a0, $3b, $8b, $9a, $3b, $85, $f9, $83, $7f, $a0, $31, $89, $f9, $9a, $31, $8d
	db $ff, $12
	dw @song0ref546
	db $78, $31, $8d, $7f, $9c, $31, $87, $f9
	db $ff, $0c
	dw @song0ref551
	db $68, $01, $84, $32, $8b, $3e, $8b, $31, $8b, $3d, $8b, $2f, $8b, $3b, $8b, $2d, $8b, $39, $8b, $68, $00, $a0
@song0ref611:
	db $31, $89, $f9, $7d, $31, $8b, $62, $2f, $2f, $89, $62, $3b, $3b, $89, $7c, $87, $7d, $87, $7e, $87, $7f, $8d, $f9, $8f
	db $ff, $11
	dw @song0ref611
	db $ff, $11
	dw @song0ref611
	db $68, $01, $92, $3e, $93, $f9, $83, $40, $93, $f9, $83, $3d, $89, $f9, $3e, $9d, $f9, $87
	db $ff, $1d
	dw @song0ref362
	db $ff, $0b
	dw @song0ref378
	db $ff, $0c
	dw @song0ref373
	db $ff, $0c
	dw @song0ref400
	db $68, $01
	db $ff, $1d
	dw @song0ref365
	db $ff, $0b
	dw @song0ref378
	db $ff, $0c
	dw @song0ref373
	db $ff, $0c
	dw @song0ref400
	db $fd
	dw @song0ch1loop
@song0ch2:
	db $80
@song0ref689:
	db $23, $f7, $e5, $1e, $ed, $2a, $ed, $23, $f7, $e5, $1e, $ed, $2a, $ed
@song0ch2loop:
	db $80, $23, $97, $00, $2f, $89, $00, $23, $8b, $00, $8b, $23, $8b, $2f, $89, $00, $8d, $23, $97, $00, $2f, $89, $00, $8d
	db $23, $89, $00, $8d
@song0ref732:
	db $2f, $89, $00, $8d, $21, $97, $00, $2d, $89, $00, $21, $89, $00, $8d, $21, $89, $00, $2d, $8b, $00, $8b, $21, $89, $00
	db $8d
@song0ref757:
	db $2d, $89, $00, $8d, $21, $89, $00, $21, $89, $00, $2d, $8b, $00, $8b, $1f, $97, $00, $2b, $89, $00
@song0ref777:
	db $1f, $89, $00, $8d, $1f, $89, $00, $2b, $89, $00, $8d, $1f, $89, $00, $1f, $89, $00, $2b, $89, $00, $8d, $1f, $8b, $00
	db $8b, $2b
@song0ref803:
	db $89, $00, $8d
@song0ref806:
	db $1e, $89, $00, $1e, $89, $00, $2a, $89, $00, $1e, $89, $00, $8d, $1e, $89, $00, $2a, $89, $00, $8d, $1e, $89, $00, $8d
	db $2a
	db $ff, $0c
	dw @song0ref803
	db $8d, $23, $97, $00, $2f, $8b, $23, $89, $00, $8d, $23, $8b, $2f, $89, $00, $8d, $23, $89, $00, $23, $89, $00, $2f, $8b
	db $00, $8b, $23, $8b, $00, $8b
	db $ff, $12
	dw @song0ref732
	db $89, $00, $8d, $21, $8b, $00, $8b
	db $ff, $0b
	dw @song0ref757
	db $89, $00, $8d, $1f, $97, $00, $2b, $8b
	db $ff, $16
	dw @song0ref777
	db $89, $00, $8d, $2b, $8b, $00, $8b
	db $ff, $0a
	dw @song0ref806
	db $8b, $00, $8b, $1e, $89, $00, $2a, $89, $00, $8d, $1e, $8b, $2a, $89, $00, $20, $89, $00, $2c, $89, $00, $22, $89, $00
	db $2e, $89, $00, $25, $89, $00, $31, $89, $00
@song0ref931:
	db $23, $a5, $00, $23, $a5, $00, $23, $89, $00, $2f, $8b, $21, $a5, $00, $21, $a5, $00, $21, $8b, $2d, $89
@song0ref952:
	db $00, $1f, $a5, $00, $1f, $a5, $00, $1f, $89, $00, $2b
@song0ref963:
	db $89, $00, $21, $a5, $00, $21, $a5, $00, $21, $89, $00, $2d, $8b
	db $ff, $0a
	dw @song0ref931
	db $ff, $09
	dw @song0ref963
	db $97
	db $ff, $0e
	dw @song0ref952
	db $97, $00, $2d, $97, $00, $21, $89, $00, $21, $89, $00, $2d, $97, $00
	db $ff, $0e
	dw @song0ref689
	db $fd
	dw @song0ch2loop
@song0ch3:
	db $f7, $f7, $f7, $a1, $94, $21, $8d, $00, $a3, $f7, $f7, $f7, $a1
@song0ref1019:
	db $21, $8d, $00, $89, $21, $89, $00, $21, $89
@song0ch3loop:
	db $83, $00, $97, $94
@song0ref1033:
	db $21, $8d, $00, $a5, $21, $8d, $00, $a5, $21, $8d, $00, $a5
	db $ff, $0c
	dw @song0ref1033
@song0ref1048:
	db $21, $8d, $00, $a5, $21, $89, $00, $21, $89, $83, $00, $97
	db $ff, $0c
	dw @song0ref1033
	db $ff, $0c
	dw @song0ref1033
	db $ff, $0c
	dw @song0ref1048
	db $ff, $0c
	dw @song0ref1033
	db $ff, $0c
	dw @song0ref1033
	db $ff, $0c
	dw @song0ref1048
	db $ff, $0c
	dw @song0ref1033
	db $ff, $09
	dw @song0ref1033
	db $89, $00, $21, $8d, $00, $a5
	db $ff, $09
	dw @song0ref1019
	db $00, $21, $89, $83, $00, $97
	db $ff, $0c
	dw @song0ref1033
	db $21, $89, $00, $21, $8d, $00, $97
	db $ff, $0c
	dw @song0ref1033
	db $21, $89, $00, $21, $89, $83, $00, $97
	db $ff, $0c
	dw @song0ref1033
	db $21, $89, $00, $21, $8d, $00, $97
	db $ff, $09
	dw @song0ref1033
	db $89, $00
	db $ff, $09
	dw @song0ref1019
	db $00, $21, $89, $83, $00, $97
@song0ref1144:
	db $96
@song0ref1145:
	db $2a, $85, $00, $83, $2a, $85, $00, $9f, $2a, $85, $00, $83, $2a, $85, $00, $83, $2a, $85, $00, $91
	db $ff, $14
	dw @song0ref1145
	db $ff, $14
	dw @song0ref1145
	db $2a, $85, $00, $83, $2a, $85, $00, $9f, $94, $21, $8d, $00, $87, $9d
	db $ff, $14
	dw @song0ref1144
	db $ff, $14
	dw @song0ref1145
	db $ff, $13
	dw @song0ref1145
	db $ad, $94
	db $ff, $09
	dw @song0ref1019
	db $fd
	dw @song0ch3loop
@song0ch4:
	db $01, $f7, $e5, $01, $ed, $01, $b5, $02, $b5, $01, $f7, $e5, $01, $ed, $01, $b5, $02, $99, $02, $8b, $02, $8b
@song0ch4loop:
@song0ref1225:
	db $01, $99, $02, $8b, $01, $99, $01, $8b, $02, $99, $01, $99, $02, $99, $01, $8b, $01, $8b, $02, $99
	db $ff, $13
	dw @song0ref1225
	db $8b, $02, $8b
	db $ff, $14
	dw @song0ref1225
	db $ff, $13
	dw @song0ref1225
	db $8b, $02, $8b
	db $ff, $14
	dw @song0ref1225
	db $ff, $0f
	dw @song0ref1225
	db $99, $02, $8b, $02, $8b
	db $ff, $14
	dw @song0ref1225
	db $ff, $09
	dw @song0ref1225
	db $8b, $02, $8b, $01, $99, $01, $8b, $02, $8b, $01, $8b, $02, $8b, $02, $8b, $02, $8b
	db $ff, $0d
	dw @song0ref1225
@song0ref1297:
	db $8b, $01, $99, $01, $8b, $02, $8b, $02, $8b
	db $ff, $0d
	dw @song0ref1225
	db $ff, $09
	dw @song0ref1297
	db $ff, $0d
	dw @song0ref1225
	db $ff, $09
	dw @song0ref1297
	db $ff, $09
	dw @song0ref1225
	db $ff, $09
	dw @song0ref1297
	db $01, $8b, $02, $8b, $02, $8b, $02, $8b, $01, $b5, $01, $ed, $01, $ed, $01, $ed, $01, $99, $02, $99, $01, $b5, $01, $ed
	db $01, $ed, $01, $d1, $01, $8b, $01, $8b, $02, $99, $02, $8b, $02, $8b, $fd
	dw @song0ch4loop
