;this file for FamiStudio Sound Engine generated by FamiStudio

music_data:
	db 1
	dw @instruments
	dw @samples-4
	dw @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4
	db <(@tempo_env_10_mid), >(@tempo_env_10_mid), 0, 0

@instruments:
	dw @env15,@env0,@env13,@env11
	dw @env4,@env0,@env2,@env11
	dw @env4,@env0,@env13,@env11
	dw @env4,@env0,@env13,@env3
	dw @env15,@env0,@env13,@env3
	dw @env16,@env0,@env13,@env14
	dw @env7,@env0,@env12,@env11
	dw @env1,@env0,@env13,@env11
	dw @env10,@env0,@env13,@env11
	dw @env8,@env0,@env13,@env11
	dw @env9,@env0,@env2,@env11
	dw @env8,@env0,@env13,@env3
	dw @env8,@env0,@env13,@env14
	dw @env6,@env0,@env12,@env11
	dw @env5,@env0,@env12,@env3

@samples:
@env0:
	db $c0,$7f,$00,$00
@env1:
	db $00,$cd,$02,$c6,$03,$c0,$00,$05
@env2:
	db $c3,$7f,$00,$00
@env3:
	db $00,$c1,$7f,$00,$01
@env4:
	db $00,$ca,$06,$c9,$00,$03
@env5:
	db $04,$cf,$7f,$00,$01
@env6:
	db $00,$cd,$c3,$00,$02
@env7:
	db $00,$cd,$cd,$c7,$02,$c1,$00,$05
@env8:
	db $00,$cc,$0e,$cb,$0f,$ca,$00,$05
@env9:
	db $00,$cd,$06,$cc,$00,$03
@env10:
	db $00,$ca,$c8,$c6,$c4,$c2,$c0,$00,$06
@env11:
	db $00,$c0,$7f,$00,$01
@env12:
	db $7f,$00,$00
@env13:
	db $c2,$7f,$00,$00
@env14:
	db $00,$c1,$c3,$c3,$c1,$c1,$bf,$bf,$c1,$c1,$c1,$00,$01
@env15:
	db $00,$c8,$0f,$c6,$10,$c4,$00,$05
@env16:
	db $00,$c8,$0f,$c7,$11,$c6,$10,$c5,$00,$07
@tempo_env_10_mid:
	db $03,$04,$06,$05,$05,$05,$80
@song0ch0:
	db $8e
@song0ref2:
	db $61, $51, $23, $1b, $8b, $00, $97, $61, $51, $23, $1b, $8b, $00, $97, $61, $51, $23, $1b, $8b, $00, $83, $61, $54, $25
	db $1c, $8b, $00, $83, $61, $51, $23, $1b, $8b, $00, $97, $61, $51, $23, $1b, $8b, $00, $83
	db $ff, $0c
	dw @song0ref2
	db $61, $51, $23, $1b, $8b, $00, $97, $6b
	db $ff, $18
	dw @song0ref2
	db $ff, $0c
	dw @song0ref2
	db $61, $51, $23, $1b, $8b, $00, $97, $6b, $94
@song0ref70:
	db $31, $85, $00
@song0ref73:
	db $30, $85, $00, $2f, $85, $00
@song0ref79:
	db $2e, $85, $00, $2d, $85, $00, $2c, $85, $00, $2b, $85, $00, $2a, $85, $00, $29, $85, $00, $28, $85, $00, $27, $85, $00
	db $26, $85, $00, $25, $85, $00, $24, $85
@song0ref111:
	db $00, $30, $8f, $00, $93, $30, $8f, $00, $a7, $30, $8f, $00, $93, $30, $8f, $00, $96, $2e, $91
@song0ch0loop:
	db $6a, <(@tempo_env_10_mid), >(@tempo_env_10_mid), $a7
@song0ref135:
	db $98, $2e, $a3, $00, $96
@song0ref140:
	db $2e, $8f, $00, $2d, $8f, $00, $93, $2e, $8f, $00, $93, $2b, $8f, $00, $93, $2b, $8f, $00, $2e, $8f, $00, $93, $92, $32
	db $a3, $00, $6b, $96, $30, $a5, $98, $30, $a3, $00, $96, $30, $a3, $00, $2e, $8f, $00, $92, $32, $8f, $00, $93, $96, $30
	db $cb, $00, $30, $8f, $00, $2e, $8f, $00, $30, $91, $6b, $e1, $00, $93, $30, $8f, $00, $92, $32, $b7, $00, $96, $30, $a3
	db $00, $2e, $a3, $00, $2d, $a3, $00, $6b, $2d, $8f, $00, $2e, $8f, $00, $2d, $8f, $00, $2b, $cb
	db $ff, $10
	dw @song0ref111
	db $2e, $91, $6b, $a5, $00
	db $ff, $53
	dw @song0ref135
	db $ff, $10
	dw @song0ref111
	db $2e, $91, $6b, $a7, $98, $2e, $a3, $00, $92
	db $ff, $16
	dw @song0ref140
	db $32, $a3, $00, $6b, $96
@song0ref262:
	db $30, $f3, $00, $93, $2e, $8f, $00, $29, $a3, $00, $2b, $a3, $00, $2d, $a3, $00, $30, $a3, $00, $6b, $92, $31, $a5, $98
	db $31, $a3, $00, $92, $31, $8f, $00, $96, $30, $8f, $00, $93, $92
@song0ref299:
	db $31, $8f, $00, $93, $31, $8f, $00, $31, $8f, $00, $93, $96, $2e, $a3, $00, $92, $31, $a3, $00, $6b, $43, $85, $00, $42
	db $85, $00, $41, $85, $00, $40, $85, $00, $3f, $85, $00, $3e, $85, $00, $3d, $85, $00, $3c, $85, $00, $3b, $85, $00, $3a
	db $85, $00
@song0ref349:
	db $39, $85, $00, $38, $85, $00, $37, $85, $00, $36, $85, $00, $32, $8f, $00, $93, $32, $8f, $00, $a7, $32, $8f, $00, $93
	db $32, $8f, $00, $96, $2e, $91, $fd
	dw @song0ch0loop
@song0ch1:
	db $a7, $90
@song0ref384:
	db $61, $1d, $38, $31, $87, $00, $c3, $61, $1d, $38, $31, $87, $00, $c3, $61, $1d, $38, $31, $87, $00, $c3, $61, $1d, $38
	db $31, $87, $00, $9b, $a7
	db $ff, $10
	dw @song0ref384
	db $82
	db $ff, $21
	dw @song0ref79
	db $23, $85, $00, $22, $85, $00, $21, $85
@song0ref428:
	db $00
@song0ref429:
	db $2d, $8f, $00, $93, $2d, $8f, $00, $a7, $2d, $8f, $00, $93, $2d, $8f, $00, $88, $2b, $91
@song0ch1loop:
	db $cd, $00, $88
@song0ref451:
	db $2b, $8f, $00, $29, $8f, $00, $93, $2b, $8f, $00, $93, $80, $26, $8f, $00, $93, $26, $8f, $00, $88, $2b, $8f, $00, $93
	db $2e, $a3, $00, $2c, $cb, $00, $2c, $a3, $00, $2b, $8f, $00, $2e, $8f, $00, $93, $2c, $cb, $00, $2c, $8f, $00, $2b, $8f
	db $00, $2c, $91, $e1, $00, $93, $2c, $8f, $00, $2d, $b7, $00, $2d, $a3, $00, $80, $26, $a3, $00, $26, $a3, $00, $cf, $88
	db $2d, $8f, $00, $2e, $8f, $00, $2d, $8f
	db $ff, $10
	dw @song0ref428
	db $2b, $91, $cd, $00
	db $ff, $4c
	dw @song0ref451
	db $ff, $10
	dw @song0ref428
	db $93, $8a, $2e, $df, $00
	db $ff, $16
	dw @song0ref140
	db $32, $91, $91, $00
	db $ff, $11
	dw @song0ref262
	db $91, $91, $00, $31, $cb, $00, $31, $8f, $00, $30, $8f, $00, $93
	db $ff, $0b
	dw @song0ref299
	db $2e, $a3, $00, $31, $8f, $00, $86
	db $ff, $0c
	dw @song0ref349
	db $84, $35, $85, $00, $34, $85, $00, $86, $33, $85, $00, $84, $32, $85, $00, $31, $85, $00, $86
	db $ff, $0f
	dw @song0ref73
	db $ff, $0f
	dw @song0ref429
	db $2b, $91, $fd
	dw @song0ch1loop
@song0ch2:
	db $a7, $9c
@song0ref617:
	db $61, $1a, $37, $31, $87, $00, $81, $61, $15, $2d, $2a, $87, $00, $b5, $61, $1a, $37, $31, $87, $00, $81, $61, $15, $2d
	db $2a, $87, $00, $b5
	db $ff, $0f
	dw @song0ref617
	db $8d, $a7
	db $ff, $0f
	dw @song0ref617
	db $8d, $61, $1c, $40, $36, $87, $00, $87, $61, $1b, $40, $38, $85, $00, $61, $1b, $40, $38, $85, $00, $61, $1a, $3d, $35
	db $87, $00, $87, $61, $1a, $3d, $35, $87, $00, $87, $61, $18, $3b, $34, $87, $00, $87, $61, $18, $3b, $34, $87, $00, $87
	db $61, $1a, $3a, $33, $87, $00, $83, $2e, $00, $61, $1a, $3a, $33, $87, $00, $83, $2e, $00, $37, $85, $00, $36, $85, $00
	db $35, $85, $00, $34, $85, $00, $33, $85, $00, $32, $85, $00
	db $ff, $19
	dw @song0ref70
	db $87, $00, $9b, $29, $87, $00, $9b, $61, $1b, $40, $38, $85, $00, $61, $1b, $40, $38, $85, $00, $61, $1c, $40, $36, $87
	db $00, $87, $61, $1c, $40, $36, $87, $00, $87, $61, $1c, $40, $36, $87, $00, $87, $2b, $87, $00, $87
@song0ch2loop:
	db $93, $9c
@song0ref787:
	db $2b, $85, $00, $2b, $85, $00, $2b, $87, $00, $87, $2b, $85, $00, $2b, $85, $00, $2b, $87, $00, $87
	db $ff, $14
	dw @song0ref787
	db $ff, $14
	dw @song0ref787
	db $ff, $10
	dw @song0ref787
@song0ref816:
	db $2c, $87, $00, $87, $2c, $85, $00, $2c, $85, $00, $2c, $87, $00, $87, $2c, $85, $00, $2c, $85, $00
	db $ff, $14
	dw @song0ref816
	db $ff, $14
	dw @song0ref816
	db $ff, $0e
	dw @song0ref816
@song0ref845:
	db $29, $87, $00, $87, $93, $29, $85, $00, $29, $85, $00
@song0ref856:
	db $29, $87, $00, $87, $29, $85, $00, $29, $85, $00, $29, $87, $00, $87, $29, $85, $00, $29, $85, $00, $29, $87, $00, $87
	db $2a, $87, $00, $9b
@song0ref884:
	db $2a, $85, $00, $2a, $85, $00
@song0ref890:
	db $2a, $87, $00, $87, $2a, $85, $00, $2a, $85, $00, $2a, $87, $00, $87
	db $ff, $10
	dw @song0ref884
@song0ref907:
	db $93, $2b, $87, $00, $87, $2d, $87, $00, $87, $2b, $87, $00, $87, $2e, $87, $00, $87, $2b, $87, $00, $9b, $29, $87, $00
	db $9b, $29, $87, $00, $9b, $29, $85, $00, $29, $85, $00, $29, $87, $00, $9b, $29, $87, $00, $87, $2b, $87, $00, $87, $93
	db $ff, $14
	dw @song0ref787
	db $ff, $14
	dw @song0ref787
	db $ff, $14
	dw @song0ref787
	db $ff, $10
	dw @song0ref787
	db $ff, $14
	dw @song0ref816
	db $ff, $14
	dw @song0ref816
	db $ff, $14
	dw @song0ref816
	db $ff, $0e
	dw @song0ref816
	db $ff, $3b
	dw @song0ref845
	db $ff, $10
	dw @song0ref884
	db $ff, $2b
	dw @song0ref907
	db $27, $87, $00, $87, $93
@song0ref993:
	db $27, $85, $00, $27, $85, $00, $27, $87, $00, $87, $27, $87, $00, $87, $27, $87, $00, $87
	db $ff, $12
	dw @song0ref993
	db $ff, $12
	dw @song0ref993
	db $ff, $0e
	dw @song0ref993
	db $ff, $0f
	dw @song0ref856
	db $87, $00, $87
	db $ff, $0f
	dw @song0ref856
	db $87, $00, $87
	db $ff, $0f
	dw @song0ref856
	db $87, $00, $87
	db $ff, $0f
	dw @song0ref856
	db $87, $00, $87
	db $ff, $0e
	dw @song0ref890
	db $2a, $87, $00, $87
	db $ff, $0e
	dw @song0ref890
	db $2a, $87, $00, $87
	db $ff, $0e
	dw @song0ref890
	db $2a, $87, $00, $87
	db $ff, $0e
	dw @song0ref890
	db $2a, $87, $00, $87, $2b, $85, $00, $2b, $85, $00, $2b, $85, $00, $89, $2b, $85, $00, $89, $2b, $85, $00, $2b, $85, $00
	db $89, $2b, $85, $00, $2b, $85, $00, $89, $2b, $85, $00, $2b, $85, $00, $2a, $87, $00, $9b, $2a, $87, $00, $9b, $40, $61
	db $18, $3d, $38, $83, $00, $40, $61, $18, $3d, $38, $83, $00, $40, $61, $1b, $3d, $36, $85, $00, $87, $40, $61, $1b, $3d
	db $36, $85, $00, $87, $40, $61, $1b, $3d, $36, $85, $00, $87, $2b, $87, $00, $87, $fd
	dw @song0ch2loop
@song0ch3:
	db $a7, $8c
@song0ref1161:
	db $23, $8d, $00, $bd, $23, $8d, $00, $bd, $23, $8d, $00, $bd, $23, $8d, $00, $95, $a7
	db $ff, $10
	dw @song0ref1161
@song0ref1181:
	db $2d, $20, $23, $26, $00, $2d, $20, $23, $26, $00, $2d, $20, $23, $26, $00, $2d, $20, $23, $26, $00, $2a, $2d, $20, $23
	db $00, $2a, $2d, $20, $23, $00, $2a, $2d, $20, $23, $00, $2a, $2d, $20, $23, $00, $28, $2b, $2e, $21, $00, $28, $2b, $2e
	db $21, $00, $28, $2b, $2e, $21, $00, $26, $29, $2c, $2f, $00, $26, $29, $2c, $2f, $00, $26, $29, $2c, $2f, $00, $23, $8d
	db $00, $95, $23, $8d, $00, $a9, $23, $8d, $00, $95, $23, $8d, $00, $81, $23, $8d, $00, $81
@song0ch3loop:
	db $9a
@song0ref1273:
	db $2b, $83, $00, $8b, $2b, $83, $00, $81, $2b, $83, $00, $81, $8c, $25, $8f, $00, $9a, $2b, $83, $00, $81, $2b, $83, $00
	db $81
	db $ff, $17
	dw @song0ref1273
	db $ff, $17
	dw @song0ref1273
	db $ff, $17
	dw @song0ref1273
	db $ff, $17
	dw @song0ref1273
	db $ff, $17
	dw @song0ref1273
	db $ff, $17
	dw @song0ref1273
	db $ff, $17
	dw @song0ref1273
	db $ff, $17
	dw @song0ref1273
	db $ff, $17
	dw @song0ref1273
	db $ff, $17
	dw @song0ref1273
	db $ff, $17
	dw @song0ref1273
	db $ff, $17
	dw @song0ref1273
	db $ff, $17
	dw @song0ref1273
	db $ff, $17
	dw @song0ref1273
	db $ff, $17
	dw @song0ref1273
	db $ff, $17
	dw @song0ref1273
	db $ff, $17
	dw @song0ref1273
	db $ff, $17
	dw @song0ref1273
	db $ff, $17
	dw @song0ref1273
	db $ff, $17
	dw @song0ref1273
	db $ff, $17
	dw @song0ref1273
	db $ff, $17
	dw @song0ref1273
	db $ff, $17
	dw @song0ref1273
	db $ff, $17
	dw @song0ref1273
	db $ff, $17
	dw @song0ref1273
	db $ff, $17
	dw @song0ref1273
	db $ff, $17
	dw @song0ref1273
	db $ff, $17
	dw @song0ref1273
	db $ff, $17
	dw @song0ref1273
	db $ff, $17
	dw @song0ref1273
	db $ff, $17
	dw @song0ref1273
	db $ff, $17
	dw @song0ref1273
	db $ff, $17
	dw @song0ref1273
	db $ff, $17
	dw @song0ref1273
	db $ff, $17
	dw @song0ref1273
	db $ff, $17
	dw @song0ref1273
	db $ff, $17
	dw @song0ref1273
	db $ff, $17
	dw @song0ref1273
	db $ff, $17
	dw @song0ref1273
	db $ff, $17
	dw @song0ref1273
	db $ff, $17
	dw @song0ref1273
	db $ff, $17
	dw @song0ref1273
	db $ff, $17
	dw @song0ref1273
	db $8c
	db $ff, $5a
	dw @song0ref1181
	db $fd
	dw @song0ch3loop
@song0ch4:
	db $f7, $f7, $cf, $f7, $f7, $cf, $f7, $f7, $cf
@song0ch4loop:
@song0ref1444:
	db $f7, $f7, $cf, $f7, $f7, $cf, $f7, $f7, $cf, $f7, $f7, $cf
	db $ff, $0c
	dw @song0ref1444
	db $ff, $0c
	dw @song0ref1444
	db $fd
	dw @song0ch4loop
