/** This file is generated by build_music.py */

#ifndef _CREDIT_MUSIC_H
#define _CREDIT_MUSIC_H

#include <stdint.h>
#include <stddef.h>
#include "dwr_types.h"

struct music_data {
    const uint8_t *start;
    const size_t size;
};

void add_music(dw_rom* rom, int track);
const extern size_t track_count;

#endif
