/** This file is generated by build_expansion.py */
#ifndef _EXPANSION_H_
#define _EXPANSION_H_

#include "dwr_types.h"

enum hooktype {
    DIALOGUE,
    JSR = 0x20,
    JMP = 0x4c,
};

enum subroutine {
  START_DWR_CREDITS = 0xC1BF,
  INC_ATTACK_CTR = 0xC1F2,
  INC_CRIT_CTR = 0xC1F9,
  INC_MISS_CTR = 0xC200,
  INC_DODGE_CTR = 0xC207,
  INC_BONK_CTR = 0xC20E,
  BLOCKED_IN_FRONT = 0xC215,
  PLAYER_AMBUSHED = 0xC21D,
  INC_COUNTER = 0xC223,
  INC_ENEMY_DEATH_CTR = 0xC232,
  INC_DEATH_CTR = 0xC240,
  COUNT_WIN = 0xC24B,
  COUNT_ENCOUNTER = 0xC253,
  INC_MON_COUNTER = 0xC259,
  COUNT_SPELL_USE = 0xC268,
  SORT_INVENTORY = 0xC274,
  TORCH_IN_BATTLE = 0xC2B1,
  THREES_COMPANY_CHECK = 0xC2F9,
  STORE_PRINCESS_ITEM = 0xC30B,
  CURSED_PRINCESS_CHECK = 0xC310,
  SCARED_SLIMES = 0xC325,
  INIT_SAVE_RAM = 0xC332,
  DISPLAY_DEATHS = 0xC33C,
  COUNT_FRAME = 0xC35D,
  SNAPSHOT_TIMER = 0xC384,
  MODIFY_RUN_RATE = 0xC392,
  SCALE_MSLIME_XP = 0xC3A2,
  SCALED_MSLIME_HOOK_POINT = 0xE94B,
};

void add_hook(dw_rom *rom, enum hooktype type, uint16_t address,
              enum subroutine to_addr);
void patch_free_3a(dw_rom *rom);
void patch_free_3b(dw_rom *rom);
void patch_free_3c(dw_rom *rom);
void patch_handle_2_byte_xp_gold(dw_rom *rom);
void patch_free_3d(dw_rom *rom);
void fill_expansion(dw_rom *rom);

#endif
